Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine ("Upa Cavalinho");
Console.ResetColor ();
Console.WriteLine ("");
Console.WriteLine("Pocotó, pocotó, pocotó, pocotó");
Console.WriteLine("Pocotó, pocotó, pocotó, pocotó");
Console.WriteLine("Upa, cavalinho");
Console.WriteLine ("");
Console.WriteLine("Upa, cavalinho");
Console.WriteLine("Pocotó, pocotó, pocotó, pocotó");
Console.WriteLine("Upa, cavalinho");
Console.WriteLine("Piuí, piuí, piuí, piuí");
Console.WriteLine ("");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Lá vem o trenzinho");
Console.WriteLine("Lá vem o trenzinho");
Console.WriteLine("piuí, piuí, piuí");
Console.ResetColor ();
Console.WriteLine ("");
Console.WriteLine("Lá vem o trenzinho");
Console.WriteLine ("Lá vem o trenzinho");
Console.WriteLine ("Bem-te-vi, bem-te-vi");
Console.WriteLine ("");
Console.WriteLine ("Bem-te-vi, bem-te-vi");
Console.WriteLine ("Olha o passarinho");
Console.WriteLine("Olha o passarinho");
Console.WriteLine ("");
Console.WriteLine("Bem-te-vi, bem-te-vi");
Console.WriteLine("Bem-te-vi, bem-te-vi");
Console.WriteLine("Olha o passarinho");
Console.WriteLine("Olha o passarinho");